"""initial_tables

Revision ID: a90cfcbeba81
Revises: 
Create Date: 2026-04-11 14:13:02.128951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a90cfcbeba81'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.String(length=50), nullable=True),
    sa.Column('barcode', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('uom', sa.String(length=20), nullable=False),
    sa.Column('cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('group_name', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('balance_qty', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_code', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_products_description', 'products', ['description'], unique=False)
    op.create_index('idx_products_group', 'products', ['group_name'], unique=False)
    op.create_index(op.f('ix_products_barcode'), 'products', ['barcode'], unique=True)
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('bank_account', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=100), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_by', sa.String(length=100), nullable=True),
    sa.Column('image_urls', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('payment_terms', sa.String(length=100), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('discount_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('grand_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('raw_extraction', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('excel_file_url', sa.String(length=500), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'processing', 'done', 'failed')", name='ck_invoices_status'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoice_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('line_number', sa.Integer(), nullable=True),
    sa.Column('extracted_name', sa.String(length=500), nullable=True),
    sa.Column('extracted_barcode', sa.String(length=50), nullable=True),
    sa.Column('extracted_qty', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('extracted_uom', sa.String(length=20), nullable=True),
    sa.Column('extracted_unit_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('extracted_discount', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('extracted_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('matched', sa.Boolean(), nullable=False),
    sa.Column('match_confidence', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('match_method', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_invoice_items_invoice', 'invoice_items', ['invoice_id'], unique=False)
    op.create_index('idx_invoice_items_product', 'invoice_items', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_invoice_items_product', table_name='invoice_items')
    op.drop_index('idx_invoice_items_invoice', table_name='invoice_items')
    op.drop_table('invoice_items')
    op.drop_table('invoices')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_products_barcode'), table_name='products')
    op.drop_index('idx_products_group', table_name='products')
    op.drop_index('idx_products_description', table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
